// Styles are theme-aware - call buildStyles(theme) to get the full set
export function buildStyles(t) {
  return {
    app: {
      minHeight: '100vh',
      background: t.bg,
      color: t.text,
      paddingBottom: 80,
      transition: 'background 0.25s ease, color 0.25s ease',
    },
    shell: {
      maxWidth: 480,
      margin: '0 auto',
      paddingBottom: 80,
      minHeight: '100vh',
    },
    page: {
      padding: '24px 20px 40px',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      marginBottom: 24,
    },
    headerEyebrow: {
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 2,
      color: t.textDim,
      marginBottom: 4,
    },
    headerTitle: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: 36,
      fontWeight: 500,
      margin: 0,
      letterSpacing: -0.5,
      color: t.text,
    },
    heroCard: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 16,
      padding: 24,
      cursor: 'pointer',
      position: 'relative',
      overflow: 'hidden',
    },
    heroLabel: {
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      color: t.textDim,
      marginBottom: 8,
    },
    heroAmount: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: 44,
      fontWeight: 500,
      letterSpacing: -1,
      lineHeight: 1,
      color: t.text,
    },
    heroFoot: {
      display: 'flex',
      justifyContent: 'space-between',
      marginTop: 16,
      fontSize: 12,
      color: t.textDim,
    },
    warningBar: {
      marginTop: 14,
      padding: '8px 12px',
      background: t.expenseBg,
      border: `1px solid ${t.expense}`,
      borderRadius: 8,
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      fontSize: 12,
      color: t.expense,
      fontWeight: 500,
    },
    sectionHead: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 28,
      marginBottom: 12,
    },
    h2: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: 20,
      fontWeight: 500,
      margin: 0,
      color: t.text,
    },
    iconBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      border: `1px solid ${t.border}`,
      background: 'transparent',
      color: t.accent,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBtnLg: {
      width: 44,
      height: 44,
      borderRadius: 22,
      border: `1px solid ${t.accent}`,
      background: t.accentSoft,
      color: t.accent,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    accountRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '14px 16px',
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      cursor: 'pointer',
    },
    accountDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    accountMeta: {
      fontSize: 11,
      color: t.textFaint,
      marginTop: 2,
    },
    accountBal: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: 20,
      fontWeight: 500,
      color: t.text,
    },
    quickGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 10,
      marginTop: 4,
    },
    quickCard: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      padding: 16,
      cursor: 'pointer',
    },
    summaryGrid2: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 10,
    },
    summaryGrid3: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr 1fr',
      gap: 8,
    },
    summaryCell: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      padding: '12px 14px',
    },
    jobCard: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      padding: '14px 16px',
      cursor: 'pointer',
    },
    billCard: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      padding: '12px 14px',
      cursor: 'pointer',
    },
    toggleRow: {
      display: 'flex',
      gap: 8,
      marginBottom: 16,
      flexWrap: 'wrap',
    },
    monthRow: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      padding: 14,
    },
    monthHeader: {
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      color: t.textDim,
      marginTop: 18,
      marginBottom: 10,
      paddingBottom: 6,
      borderBottom: `1px solid ${t.border}`,
    },
    modalOverlay: {
      position: 'fixed',
      inset: 0,
      background: 'rgba(0, 0, 0, 0.55)',
      zIndex: 100,
      display: 'flex',
      alignItems: 'flex-end',
      justifyContent: 'center',
      animation: 'fadeIn 0.2s',
    },
    modalSheet: {
      background: t.bg,
      width: '100%',
      maxWidth: 480,
      maxHeight: '90vh',
      overflowY: 'auto',
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: '12px 20px 32px',
      border: `1px solid ${t.border}`,
      animation: 'slideUp 0.25s ease-out',
    },
    modalHandle: {
      width: 40,
      height: 4,
      background: t.borderStrong,
      borderRadius: 2,
      margin: '0 auto 16px',
    },
    formActions: {
      display: 'flex',
      gap: 10,
      marginTop: 22,
    },
    input: {
      width: '100%',
      padding: '12px 14px',
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      color: t.text,
      fontSize: 15,
      fontFamily: 'inherit',
      boxSizing: 'border-box',
    },
    bigInput: {
      width: '100%',
      padding: '8px 0',
      background: 'transparent',
      border: 'none',
      borderBottom: `1px solid ${t.border}`,
      color: t.text,
      fontSize: 36,
      fontFamily: "'Cormorant Garamond', serif",
      fontWeight: 500,
      boxSizing: 'border-box',
      outline: 'none',
    },
    segGroup: {
      display: 'flex',
      gap: 4,
      background: t.bgElev,
      borderRadius: 10,
      padding: 4,
      border: `1px solid ${t.border}`,
    },
    btnPrimary: {
      flex: 1,
      padding: '14px',
      background: t.accent,
      color: t.bg,
      border: 'none',
      borderRadius: 10,
      fontSize: 14,
      fontWeight: 600,
      textTransform: 'uppercase',
      letterSpacing: 1,
      cursor: 'pointer',
    },
    btnGhost: {
      flex: 1,
      padding: '14px',
      background: 'transparent',
      color: t.textDim,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      fontSize: 14,
      fontWeight: 500,
      textTransform: 'uppercase',
      letterSpacing: 1,
      cursor: 'pointer',
    },
    btnDanger: {
      padding: '14px 16px',
      background: 'transparent',
      color: t.expense,
      border: `1px solid ${t.expense}`,
      borderRadius: 10,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    reconcileBox: {
      background: t.bgElev,
      border: `1px solid ${t.accent}`,
      borderRadius: 12,
      padding: 18,
      marginBottom: 4,
    },
    previewBox: {
      marginTop: 10,
      padding: 14,
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
    },
    nav: {
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      display: 'flex',
      background: t.bg + 'ee',
      backdropFilter: 'blur(20px)',
      WebkitBackdropFilter: 'blur(20px)',
      borderTop: `1px solid ${t.border}`,
      maxWidth: 480,
      margin: '0 auto',
      zIndex: 50,
    },
  };
}
