// Styles are theme-aware and respect the text scale setting.
// Pass the scale factor to scale every font-size proportionally.
// isDesktop controls layout — wider shell, sidebar nav.

export function buildStyles(t, scale = 1, isDesktop = false) {
  const sz = (n) => Math.round(n * scale);

  return {
    app: {
      minHeight: '100vh',
      background: t.bg,
      color: t.text,
      paddingBottom: 80,
      transition: 'background 0.25s ease, color 0.25s ease',
    },
    shell: {
      maxWidth: isDesktop ? 1100 : 480,
      margin: '0 auto',
      paddingBottom: isDesktop ? 24 : 80,
      paddingLeft: isDesktop ? 220 : 0,  // Space for sidebar nav on desktop
      minHeight: '100vh',
      position: 'relative',
    },
    page: {
      padding: isDesktop ? '32px 40px 40px' : '24px 20px 40px',
      maxWidth: isDesktop ? 880 : '100%',
    },
    header: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'flex-end',
      marginBottom: 24,
    },
    headerEyebrow: {
      fontSize: sz(11),
      textTransform: 'uppercase',
      letterSpacing: 2,
      color: t.textDim,
      marginBottom: 4,
      fontWeight: 500,
    },
    headerTitle: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: sz(36),
      fontWeight: t.weightHeading,
      margin: 0,
      letterSpacing: -0.5,
      color: t.text,
    },
    heroCard: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 16,
      padding: 24,
      cursor: 'pointer',
      position: 'relative',
      overflow: 'hidden',
    },
    heroLabel: {
      fontSize: sz(11),
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      color: t.textDim,
      marginBottom: 8,
      fontWeight: 500,
    },
    heroAmount: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: sz(44),
      fontWeight: t.weightAmount,
      letterSpacing: -1,
      lineHeight: 1,
      color: t.text,
    },
    heroFoot: {
      display: 'flex',
      justifyContent: 'space-between',
      marginTop: 16,
      fontSize: sz(13),
      color: t.textDim,
      fontWeight: 500,
    },
    warningBar: {
      marginTop: 14,
      padding: '10px 12px',
      background: t.expenseBg,
      border: `1px solid ${t.expense}`,
      borderRadius: 8,
      display: 'flex',
      alignItems: 'center',
      gap: 8,
      fontSize: sz(13),
      color: t.expense,
      fontWeight: 600,
    },
    sectionHead: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 28,
      marginBottom: 12,
    },
    h2: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: sz(20),
      fontWeight: t.weightHeading,
      margin: 0,
      color: t.text,
    },
    iconBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      border: `1px solid ${t.border}`,
      background: 'transparent',
      color: t.accent,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    iconBtnLg: {
      width: 44,
      height: 44,
      borderRadius: 22,
      border: `1px solid ${t.accent}`,
      background: t.accentSoft,
      color: t.accent,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    accountRow: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: '14px 16px',
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      cursor: 'pointer',
    },
    accountDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    accountMeta: {
      fontSize: sz(11),
      color: t.textFaint,
      marginTop: 2,
    },
    accountBal: {
      fontFamily: "'Cormorant Garamond', serif",
      fontSize: sz(20),
      fontWeight: t.weightAmount,
      color: t.text,
    },
    quickGrid: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 10,
      marginTop: 4,
    },
    quickCard: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      padding: 16,
      cursor: 'pointer',
    },
    summaryGrid2: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr',
      gap: 10,
    },
    summaryGrid3: {
      display: 'grid',
      gridTemplateColumns: '1fr 1fr 1fr',
      gap: 8,
    },
    summaryCell: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      padding: '12px 14px',
    },
    jobCard: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      padding: '14px 16px',
      cursor: 'pointer',
    },
    billCard: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      padding: '12px 14px',
      cursor: 'pointer',
    },
    toggleRow: {
      display: 'flex',
      gap: 8,
      marginBottom: 16,
      flexWrap: 'wrap',
    },
    monthRow: {
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
      padding: 14,
    },
    monthHeader: {
      fontSize: sz(11),
      textTransform: 'uppercase',
      letterSpacing: 1.5,
      color: t.textDim,
      marginTop: 18,
      marginBottom: 10,
      paddingBottom: 6,
      borderBottom: `1px solid ${t.border}`,
      fontWeight: 600,
    },
    modalOverlay: {
      position: 'fixed',
      inset: 0,
      background: 'rgba(0, 0, 0, 0.55)',
      zIndex: 100,
      display: 'flex',
      alignItems: isDesktop ? 'center' : 'flex-end',
      justifyContent: 'center',
      animation: 'fadeIn 0.2s',
      padding: isDesktop ? 20 : 0,
    },
    modalSheet: {
      background: t.bg,
      width: '100%',
      maxWidth: 480,
      maxHeight: isDesktop ? '85vh' : '90vh',
      overflowY: 'auto',
      borderRadius: isDesktop ? 16 : 0,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      padding: '12px 20px 32px',
      border: `1px solid ${t.border}`,
      animation: isDesktop ? 'fadeIn 0.2s' : 'slideUp 0.25s ease-out',
    },
    modalHandle: {
      width: 40,
      height: 4,
      background: t.borderStrong,
      borderRadius: 2,
      margin: '0 auto 16px',
    },
    formActions: {
      display: 'flex',
      gap: 10,
      marginTop: 22,
    },
    input: {
      width: '100%',
      padding: '12px 14px',
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      color: t.text,
      fontSize: sz(15),
      fontFamily: 'inherit',
      boxSizing: 'border-box',
    },
    bigInput: {
      width: '100%',
      padding: '8px 0',
      background: 'transparent',
      border: 'none',
      borderBottom: `1px solid ${t.border}`,
      color: t.text,
      fontSize: sz(36),
      fontFamily: "'Cormorant Garamond', serif",
      fontWeight: t.weightAmount,
      boxSizing: 'border-box',
      outline: 'none',
    },
    segGroup: {
      display: 'flex',
      gap: 4,
      background: t.bgElev,
      borderRadius: 10,
      padding: 4,
      border: `1px solid ${t.border}`,
    },
    btnPrimary: {
      flex: 1,
      padding: '14px',
      background: t.accent,
      color: t.bg,
      border: 'none',
      borderRadius: 10,
      fontSize: sz(14),
      fontWeight: 600,
      textTransform: 'uppercase',
      letterSpacing: 1,
      cursor: 'pointer',
    },
    btnGhost: {
      flex: 1,
      padding: '14px',
      background: 'transparent',
      color: t.textDim,
      border: `1px solid ${t.border}`,
      borderRadius: 10,
      fontSize: sz(14),
      fontWeight: 500,
      textTransform: 'uppercase',
      letterSpacing: 1,
      cursor: 'pointer',
    },
    btnDanger: {
      padding: '14px 16px',
      background: 'transparent',
      color: t.expense,
      border: `1px solid ${t.expense}`,
      borderRadius: 10,
      cursor: 'pointer',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    reconcileBox: {
      background: t.bgElev,
      border: `1px solid ${t.accent}`,
      borderRadius: 12,
      padding: 18,
      marginBottom: 4,
    },
    previewBox: {
      marginTop: 10,
      padding: 14,
      background: t.bgElev,
      border: `1px solid ${t.border}`,
      borderRadius: 12,
    },
    nav: isDesktop ? {
      position: 'fixed',
      top: 0,
      left: 'max(0px, calc((100vw - 1100px) / 2))',
      width: 200,
      height: '100vh',
      display: 'flex',
      flexDirection: 'column',
      background: t.bgElev,
      borderRight: `1px solid ${t.border}`,
      zIndex: 50,
      padding: '24px 16px',
      gap: 4,
    } : {
      position: 'fixed',
      bottom: 0,
      left: 0,
      right: 0,
      display: 'flex',
      background: t.bg + 'ee',
      backdropFilter: 'blur(20px)',
      WebkitBackdropFilter: 'blur(20px)',
      borderTop: `1px solid ${t.border}`,
      maxWidth: 480,
      margin: '0 auto',
      zIndex: 50,
    },
    isDesktop,
    sz,  // expose the scale function for components
  };
}
